### ISSUE TITLE
why are the release tarbals instead of tar.gz

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/bosh-backup-and-restore#10]
im incorporating bbr in a bosh release
but the tar file is 24mb.
im wondering why this is not compressed.

**Comment by thereses** [comment]
Hi, we used to compress the data on the VM the backup was run on but it causes performance problems on the VM. we didn't add it on the jumpbox because it's quite easy to add a compression step after the backup artifact is created.

**Comment by ramonskie** [comment]
i didn't meant the backup :)
i meant the bbr-cli release it self
https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases
