### ISSUE TITLE
bbr not working thru socks5 tunnel

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-backup-and-restore#11]
I have a socks5 tunnel running, I have `export BOSH_ALL_PROXY=socks5://localhost:9999` set, and my `bosh` commands run thru the tunnel just fine, but I tried `bbr` (via https://www.starkandwayne.com/blog/bucc-bbr-finally/) and its failing:

```
finding scripts failed on bosh/0: ssh.Run failed: ssh.Stream failed: ssh.Dial failed: dial tcp 10.10.1.4:22: connect: connection refused
```

`10.10.1.4` is the IP of my BOSH, but it is only accessible via the SOCKS5 tunnel. Should this "just work" if I have `$BOSH_ALL_PROXY` set?

**Comment by thereses** [comment]
Hi @drnic thanks for filing this issue. We will add support for proxies. The work isn't top of backlog but we'll get to it soon.

**Comment by tcdowney** [comment]
Just as another anecdote, this should also make using `bbr` easier for bbl users. We're currently using `sshuttle` to get a locally running `bbr` tunneled through the bbl jumpbox.

**Comment by jaresty** [comment]
👍 We also were looking to use this feature.

**Comment by jamesjoshuahill** [comment]
@drnic We introduced support for `$BOSH_ALL_PROXY` in bbr [v1.2.6](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.2.6). See the BOSH docs on [tunnelling](https://bosh.io/docs/cli-tunnel/).

Note: If you are using bosh bootloader, bbr also supports the `ssh+socks5` scheme, which is generated by `bbl print-env`. With this scheme, you do not need to create the ssh tunnel beforehand as bbr will do it for you.
