### ISSUE TITLE
Deployment not restoring. Stemcell not found

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-incubator/bosh-backup-and-restore#12]
I'm restoring a BOSH that contains a single deployment with a single VM. The deployment's instance fails to start up, and when I run `bosh cck` on it the error is:

```
Task 13 | 04:57:17 | Applying problem resolutions: VM for 'my-little/4e4d8fb3-2cbc-419e-9fac-8ded0b486464 (0)' missing. (missing_vm 1): Recreate VM and wait for processes to start (00:00:00)
                   L Error: CPI error 'Bosh::Clouds::CloudError' with message 'Expected to find stemcell '{{5947a28b-063d-4239-725c-31582cde24dd}}'' in 'create_vm' CPI method
```

The ID does look the same as from the stemcells list:

```
$ bosh stemcells
Using environment '192.168.50.6' as client 'admin'

Name                                         Version  OS             CPI  CID
bosh-warden-boshlite-ubuntu-trusty-go_agent  3541.8*  ubuntu-trusty  -    5947a28b-063d-4239-725c-31582cde24dd
```

Is there something dodgy with the `{{...}}` around the stemcell ID? Or any other ideas why the deployment didn't restore ok?

**Update:** I deleted + redeployed the deployment and got a similar error. It was resolved by running `bosh upload-stemcell --fix path/to/stemcell`. Can you think why the stemcell records might not have been restored correctly?

**Update:** I've gone thru the entire process I've written up in draft blog post https://starkandwayne.com/blog/p/3afbd38d-7028-40c8-97d3-bee5f1515219/ again and am getting the same result.

**Comment by drnic** [comment]
@rkoster I'm using BUCC's BBR system - has it correctly restored stemcells for you; or did you need to `bosh upload-stemcell --fix` first?

**Comment by henryaj** [comment]
That said, if you're just doing `bucc down` (which as far as I can see is just a `bosh delete-env`) then the stemcell should hang around in your IaaS, so a restore should just work... Strange.

**Comment by drnic** [comment]
Ok I think I understand more about what to expect from a BBR restore. I’ll close for now.

**Comment by drnic** [comment]
@henryaj it was a bosh-lite/bucc-lite so they were missing warden stemcells, which are ephemeral within the previously existing VM

**Comment by henryaj** [comment]
Aha! I didn't know that.
