### ISSUE TITLE
sudo tty present and no askpass program specified error

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry-incubator/bosh-backup-and-restore#14]
After enhancing our director to include the backup-and-restore-sdk, we are attempting to use bbr to backup our director.

We are  receiving `finding scripts failed on bosh/0: sudo: no tty present and no askpass program specified - exit code 1`  in response to `./bbr director --key openstack/id_rsa --username vcap --host $BOSH_ENVIRONMENT pre-backup-check`

We find that it appears we have to set the SUDOER list to not require a password for vcap, but isn't there a better way?

**Comment by alamages** [comment]
Hi @keithkroeger 

@voelzmo is correct. You will need to create a user for `bbr` to SSH into the BOSH Director VM.

You could use the `jumpbox-user.yml` [ops file](https://github.com/cloudfoundry/bosh-deployment/blob/master/jumpbox-user.yml) in your `bosh create-env` command. Or incorporate the changes made by the ops file in your BOSH Director manifest.

The jumpbox user is documented [here](https://bosh.io/docs/jumpbox/). Then run `bbr` with username `jumpbox` and the jumpbox private key.

Best wishes
Emmanouil and @jamesjoshuahill

**Comment by keithkroeger** [comment]
Thank you @voelzmo  and @alamages for the replies.  We've successfully added users using os-conf for other needs, so this will help a lot.
