### ISSUE TITLE
bbr on windows stemcell

### ISSUE THREAD

**Issue by jgprogramming** [cloudfoundry-incubator/bosh-backup-and-restore#15]
Hey,

We use BBR in our CF deployment to backup mysql and UAA (both of these components are on linux stemcells). After adding windows cell to our Cf deployment we get this error.

`failed to find instances for deployment cf: couldn't find jobs: finding scripts failed on compute_win/4a129967-7775-43d1-9cc3-cc9b020a957d: 'sudo' is not recognized as an internal or external command`

Are there any plans to allow BBR to work with windows vms? Even ability to skip this vm would be helpful.

**Comment by alamages** [comment]
Hi @jgprogramming 

Currently, cf-deployment with windows cells is not supported by `bbr`. And there is no way to skip an instance in the deployment when running `bbr deployment backup/restore`.

Emmanouil && @jamesjoshuahill

**Comment by julian-hj** [comment]
+1 on this issue--it is blocking us from testing BBR in the persistence pipeline, and I suspect that it will block other teams soon also.  I suppose we could deploy the windows cell to a different deployment, but that would be quite a lot of work, and would result in a flaky non-standard deployment for us, so I am reluctant to go down that road.

Is it not possible to just skip windows VMs when traversing a deployment, and just emit a warning?  To me that seems like a much better behavior than failing with no way to recover.

**Comment by julian-hj** [comment]
One thought--if you are running commands via ssh, you could start your script with `Exit` which will generate an error, but not exit on unix, and will terminate the shell on windows.  (since windows is case insensitive, and Unix is not.)

If you want to not have an ugly error in your logs, then the following seems to swallow the error on Unix without causing parse errors on windows:

```
Exit 2> exit.txt
rm exit.txt
```

**Comment by alamages** [comment]
Hello @julian-hj and @jgprogramming 

We have a new [1.2.4 BBR](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.2.4) which works with windows VMs (it properly skips them without failing).

**Comment by julian-hj** [comment]
@alamages excellent news!  We shall unpause DRATS in our pipelines.  Thanks for the heads up.
