### ISSUE TITLE
Ignore backups

### ISSUE THREAD

**Issue by robtec** [cloudfoundry-incubator/bosh-backup-and-restore#17]
Hi,

Is it possible to ignore the blobstore and credhub from the backup?

I was trying to remove the entries from the `metadata` file so the restore wouldn't look for them (I had planned to remove both blobstore and credhub tars from the backup)

Sadly no joy

```
1 error occurred:
error 1:
Unable to send backup to remote machine. Got error: 2 errors occurred:
error 1:
Backup couldn't be transferred, checksum failed for bosh/0 credhub - checksums don't match for []. Checksum failed for 0 files in total
error 2:
Backup couldn't be transferred, checksum failed for bosh/0 blobstore - checksums don't match for []. Checksum failed for 0 files in total

```

**Comment by lochlainnw** [comment]
+1 on this. we are trying to do the same.

**Comment by jamesjoshuahill** [comment]
Hi @robtec 

What are you backing up using bbr?

If you are backing up a BOSH Director or a Cloud Foundry deployment it is important to backup all the components and their datastores to ensure you have a consistent and complete backup artifact.

There are a number of risks if the blobstore or Credhub are not restored. Without a blobstore there will be a number of references in component databases pointing to non-existent blobs. Likewise without Credhub, credentials will be missing.

We do not fully understand what the behaviour of a BOSH Director, or Cloud Foundry would be after an incomplete restore. And we do not know what steps would be required to repair.

Best wishes
Josh and Giuseppe (@gcapizzi)

**Comment by ChunyiLyu** [comment]
Hi @robtec, we will close this issue for now. Feel free to reopen this issue if you have further questions.
