### ISSUE TITLE
option to allow skipping backups for items stored in durable storage (ie - blobs in S3)

### ISSUE THREAD

**Issue by matthewfischer** [cloudfoundry-incubator/bosh-backup-and-restore#18]
Feature Request: Add the ability to skip/ignore parts of the backup that are backed by highly durable storage such as AWS S3.

Reasoning:

1. Running bbr causes an API outage for users of PCF. It would be nice to make this as short as possible.
2. Data stored in S3 and S3 like stores is highly durable - S3 offers 11 9s durability (99.999999999%). If users desire higher they can also make buckets multi-regional.
3. Skipping these parts of the backup would make it significantly faster and significantly smaller.

This would not have to be a recommended setting nor a default, but I believe it would make bbr much quicker and the backup's smaller, reducing costs of storage and bandwidth.

**Comment by cloudyday** [comment]
I second that.

**Comment by voelzmo** [comment]
Probably even more generic: allow to skip backup/restore for specific jobs. For whatever reasons you want to skip the script that a release author put into the release. Trusting S3 might be one of them. Having a different strategy for backup/restore for that job might be another one.

Does that sound like something useful?

**Comment by voelzmo** [comment]
From a slack conversation with @glestaris 
> One of our ongoing initiatives (although slightly paused) is about reducing the impact of backing up blobstores
As part of this initiative we’ve been looking at selective backups
We are not, atm, seeing a generic solution as useful though: we are more in the lines of giving the ability to only backup CCDB/UAADB and buildpacks, +/- packages

Tracker epic exploring the solution space: https://www.pivotaltracker.com/epic/show/4027472

**Comment by glestaris** [comment]
Hey folks,

Just to close the loop here: we just had our cf-d PR merged. In https://github.com/cloudfoundry/cf-deployment/pull/682 we introduce two new ops-files that allow platform engineers to skip backing up droplets or droplets and packages. See https://github.com/cloudfoundry/cf-deployment/tree/develop/operations/backup-and-restore.

This means that a platform engineer with sufficient automation to re-push apps after a disaster or user error (e.g.: accidentally deleted an org) will only backup buildpacks which will be a lot faster.

**Next steps:**

- We will document the tradeoffs, requirements and recovery procedures in https://www.pivotaltracker.com/story/show/162728352 (I will prioritise early next year_
- Selective backups currently only work for external blobstores (S3, GCS and Azure). In https://www.pivotaltracker.com/story/show/162666375 we are exploring how to implement selective backups for the internal, WebDAV/NFS, blobstore. (This is currently in flight).

I'll close this for now.
