### ISSUE TITLE
Option to zip blobstore before or while transmitting

### ISSUE THREAD

**Issue by cloudyday** [cloudfoundry-incubator/bosh-backup-and-restore#19]
Hello guys!

We were wondering why `bbr` transmits the backups uncompressed. 

Our blobstore is quite large and `bbr` takes very long to transmit the blobstore depending on infrastructure. Compressing it afterwards also takes extra time and space on our jumpbox. I would like to understand why the decision to transmit uncompressed was made and discuss if there are options like

1) compressing the blobstore on the director before transmitting
2) `bbr` compressing the blobstore while receiving the transmission so that space isn't wasted on disk

I can see a reason why it isn't done on the director: compression consumes CPU power and you don't want to sacrifice that power while the director is running critical operations. But this could be circumvented by scheduling `bbr` at a time when the director isn't usually busy.

Kind regards
Oliver

**Comment by MirahImage** [comment]
Hi, 

We do not plan to implement this feature for a number of reasons:
- Compressing the artifact is computationally expensive. Doing this on the director would consume all computation resources on the director and make it unresponsive. We cannot require bbr only be used at times when the director is not busy, as such times are not guaranteed to exist. 
- Blobstore artifacts consist of tar'ed binary blobs, which would not be compressed by gzip
- bbr exists to solve issues that are difficult for operators. An operator can easily compress the backup artifact on the jumpbox before transferring it elsewhere.

**Comment by cloudyday** [comment]
Hi.

 Thanks a lot for the elaborate answer.

Kind regards 
Oliver
