### ISSUE TITLE
SSH tunnel closes early when backing up large artifacts

### ISSUE THREAD

**Issue by jamesjoshuahill** [cloudfoundry-incubator/bosh-backup-and-restore#22]
This issue was originally reported in https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/21#issuecomment-424670685.

## Limitation
When `$BOSH_ALL_PROXY` is set `bbr` creates connections to the BOSH Director and deployment instances using the jumpbox as a SOCKS5 proxy.

When a backup artifact is very large—the [reported case](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/issues/21#issuecomment-425509900) was 56GB—the time taken to calculate the checksum after copying it from the remote can exceed 15 minutes. After 15 minutes of inactivity the SOCKS5 proxy connections close, so subsequent connection attempts fail causing backup to fail.

```bash
[bbr] 2018/09/25 23:09:33 INFO - Finished validity checks -- for job director on bosh/0...
[bbr] 2018/09/25 23:09:33 INFO - Finished validity checks -- for job bbr-credhubdb on bosh/0...
[bbr] 2018/09/25 23:34:17 INFO - Finished copying backup -- for job blobstore on bosh/0...
[bbr] 2018/09/25 23:34:17 INFO - Starting validity checks -- for job blobstore on bosh/0...
[bbr] 2018/09/25 23:49:01 INFO - Backup created of 192.168.0.10 on 2018-09-25 23:09:32.52464317 +0000 UTC m=+12.091158177
[bbr] 2018/09/25 23:49:01 INFO - Cleaning up...
[bbr] 2018/09/25 23:49:01 ERROR - Backup artifact clean up failed
2 errors occurred:
error 1:
1 error occurred:
error 1:
Unable to calculate backup checksum: ssh.Run failed: ssh.Stream failed: ssh.Dial failed: EOF
	
error 2:
Deployment '192.168.0.10' failed while cleaning up with error: 1 error occurred:
error 1:
Unable to clean up backup artifact: ssh.Run failed: ssh.Stream failed: ssh.Dial failed: EOF
```

This example shows the checksum and following cleanup step errors.

## Workaround
If affected by this issue you can create the SOCKS5 proxy before invoking `bbr`. Follow the BOSH CLI documentation to [establish a tunnel separately](https://bosh.io/docs/cli-tunnel/#tunnel-established-separately) and use the `ServerAliveInterval` option, for example:

```bash
$ ssh -4 -D 12345 -fNC jumpbox@jumpbox-ip -i jumpbox.key -o ServerAliveInterval=60
$ export BOSH_ALL_PROXY=socks5://localhost:12345
```

## Next steps
We are going to document this as a known limitation whilst we work with the BOSH team to explore solutions for adding keep alive to the SOCKS5 proxy connections.

Josh and @alamages

**Comment by aclevername** [comment]
We have done a spike to see fi the recent bumps to the BOSH utils and socks5 proxy packages have fixed the issue and it appears they have. This should now be fixed in version `1.5.1` and above of the BBR CLI.

Context: https://www.pivotaltracker.com/story/show/166440901

Closing.
