### ISSUE TITLE
Make sure /var/vcap/store/bbr-backup does not exist when creating a new backup

### ISSUE THREAD

**Issue by amuessig** [cloudfoundry-incubator/bosh-backup-and-restore#23]
When a bbr-backup fails due to any reason, all following backup trials also fail with the following reason:

    Directory /var/vcap/store/bbr-backup already exists on instance bosh/0

I would like to have bbr to ensure this folder is not there yet before creating a new backup.

**Comment by aclevername** [comment]
Hi @amuessig ,

After a `backup` fails we recommend that you run the `backup-cleanup` command, this will remove any leftover state from a failed backup and should allow you to run the next `backup` successfully. 

Thanks,
Jake
