### ISSUE TITLE
go get github.com/pivotal-cf/bosh-backup-and-restore fails because of permissions

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry-incubator/bosh-backup-and-restore#3]
when i try to `clone` or retrieve it with `go get`

i get a permissions denied on the following submodule
```
[submodule "fixtures/releases"]
	path = fixtures/releases
	url = git@github.com:pivotal-cf-experimental/bosh-backup-and-restore-test-releases.git
```

**Comment by tinygrasshopper** [comment]
@ramonskie thanks for letting us know, we have updated the urls. We also don't recommend go getting the project, we have added some instructions for local dev.
