### ISSUE TITLE
BBR Failure 'Unable to check size of /var/vcap/store/bbr-backup/blobstore'

### ISSUE THREAD

**Issue by keithkroeger** [cloudfoundry-incubator/bosh-backup-and-restore#31]
Our backup process runs the following commands:
```
bbr director --private-key-path bosh.pem --username bbr --host $BOSH_ENVIRONMENT backup-cleanup
bbr director --private-key-path bosh.pem --username bbr --host $BOSH_ENVIRONMENT backup
```
We have seen the following errors for the 'backup' command:
```
[bbr] 2019/09/11 07:05:41 INFO - Looking for scripts

[bbr] 2019/09/11 07:05:41 INFO - bosh/0/blobstore/backup

[bbr] 2019/09/11 07:05:41 INFO - bosh/0/blobstore/restore

[bbr] 2019/09/11 07:05:41 INFO - bosh/0/director/backup

[bbr] 2019/09/11 07:05:41 INFO - bosh/0/director/restore

[bbr] 2019/09/11 07:05:41 INFO - Running post-backup-unlock scripts...

[bbr] 2019/09/11 07:05:41 INFO - Finished running post-backup-unlock scripts.

[] 2019/09/11 07:05:41 INFO - Cleaning up...

[bbr] 2019/09/11 07:05:42 INFO - '{IP}' cleaned up



[bbr] 2019/09/11 07:05:42 INFO - Looking for scripts

[bbr] 2019/09/11 07:05:42 INFO - bosh/0/blobstore/backup

[bbr] 2019/09/11 07:05:42 INFO - bosh/0/blobstore/restore

[bbr] 2019/09/11 07:05:42 INFO - bosh/0/director/backup

[bbr] 2019/09/11 07:05:42 INFO - bosh/0/director/restore

[bbr] 2019/09/11 07:05:42 INFO - Running pre-checks for backup of {IP}...

[bbr] 2019/09/11 07:05:42 INFO - Starting backup of {IP}...

[bbr] 2019/09/11 07:05:42 INFO - Running pre-backup-lock scripts...

[bbr] 2019/09/11 07:05:42 INFO - Finished running pre-backup-lock scripts.

[bbr] 2019/09/11 07:05:42 INFO - Running backup scripts...

[bbr] 2019/09/11 07:05:42 INFO - Backing up blobstore on bosh/0...

[bbr] 2019/09/11 07:05:43 INFO - Finished backing up blobstore on bosh/0.

[bbr] 2019/09/11 07:05:43 INFO - Backing up director on bosh/0...

[bbr] 2019/09/11 07:05:44 INFO - Finished backing up director on bosh/0.

[bbr] 2019/09/11 07:05:44 INFO - Finished running backup scripts.

[bbr] 2019/09/11 07:05:44 INFO - Running post-backup-unlock scripts...

[bbr] 2019/09/11 07:05:44 INFO - Finished running post-backup-unlock scripts.

[bbr] 2019/09/11 07:05:44 INFO - Backup created of {IP} on 2019-09-11 07:05:44.671767607 +0000 UTC m=+2.469116357
[] 2019/09/11 07:05:44 INFO - Cleaning up...
1 error occurred:
error 1:
2 errors occurred:
error 1:
Unable to check size of /var/vcap/store/bbr-backup/blobstore: du: cannot access '/var/vcap/store/bbr-backup/blobstore': No such file or directory - exit code 1
```
I'm unclear where to look further to find the issue with BBR.

We are using the following releases:

- bosh-268.2.1-ubuntu-xenial-170.9.tgz
- bpm-0.12.3-ubuntu-xenial-97.17-20180919-183904-508666998-20180919183910.tgz
- backup-and-restore-sdk-release-1.7.1.tgz
- datadog-agent-boshrelease-2.5.660.tgz
- os-conf-20.tgz
- bosh-stemcell-97.12-openstack-kvm-ubuntu-xenial-go_agent.tar
- bosh-openstack-cpi-release-39.tgz

Thank you

**Comment by alamages** [comment]
Hello @keithkroeger,

I run it against a 268.6.5 BOSH and worked. I could not reproduce the issue. Just to provide some context on the failure:

Once `bbr` invokes the backup scripts from the director, it starts downloading the generated artifacts from the director VM. In this case, the output looks like:

```
...
[bbr] 2019/09/19 13:34:23 INFO - Finished running post-backup-unlock scripts.
[bbr] 2019/09/19 13:34:24 INFO - Copying backup -- 596K uncompressed -- for job director on bosh/0...
[bbr] 2019/09/19 13:34:24 INFO - Copying backup -- 12G uncompressed -- for job blobstore on bosh/0...
[bbr] 2019/09/19 13:34:24 INFO - Finished copying backup -- for job director on bosh/0...
[bbr] 2019/09/19 13:34:24 INFO - Starting validity checks -- for job director on bosh/0...
...
```

As shown above, `bbr` prints the size of the uncompressed artifacts before it downloads them. In your case, you don't get this output because bbr fails to check the size of the target artifact,  specifically the `/var/vcap/store/bbr-backup/blobstore`.

This directory should exist after a successful backup. 

Just a suggestion: `bbr backup-cleanup` should only run if a backup fails, there is no need to run it before a backup.

Questions:
- Do you run this in a CI or manually?
- Do you consistently get this error when you run `bbr director backup`?  

Without running the cleanup step, can you try and run `bbr director backup` manually (also make sure there is no CI running another bbr command on the same director at the same time)?

**Comment by keithkroeger** [comment]
Thank you, @alamages for writing.
We had run the cleanup before every backup in order to ensure that the environment was clean.
We will try to change this to only run on failure. 
One interesting point about the environment we are seeing this, it is quite small.  So, perhaps the cleanup is spawning actions that overlap the backup?

_Question Do you run this in a CI or manually?_
We manage our Director in Concourse.  As such, we use a script to run BBR.
There is only one process running the backup on a given director at a given time.

_Question Do you consistently get this error when you run bbr director backup?_
In one environment, we get this error the first time we run BBR.
If we run the same script again (concourse attempt 2), it works

_Question Are you using the latest bbr cli?_
We are using the version provided in the release noted.

**Comment by alamages** [comment]
@keithkroeger thanks for your response.

> Thank you, @alamages for writing.
> We had run the cleanup before every backup in order to ensure that the environment was clean.
> We will try to change this to only run on failure.
> One interesting point about the environment we are seeing this, it is quite small. So, perhaps the cleanup is spawning actions that overlap the backup?
>
No, cleanup should not spawn actions that overlap backup. Let me know if running cleanup on failure solves your issue.
  
> _Question Do you consistently get this error when you run bbr director backup?_
> In one environment, we get this error the first time we run BBR.
> If we run the same script again (concourse attempt 2), it works
>
Is this consistent though? Does this happen everytime/often? I mean, you get one error, one success, then one error and one success etc. If it only happened once, and then every single backup afterwards succeeds, is this still an issue for you?

> _Question Are you using the latest bbr cli?_
> We are using the version provided in the release noted.
In the releases you provide in your first comment, you don't mention which bbr cli version you are using. You only mention bosh backup and restore sdk (namely backup-and-restore-sdk-release-1.7.1.tgz) which is separated thing used in the BOSH director. Can you please make sure you use the latest bbr cli: https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases

**Comment by keithkroeger** [comment]
Hi,
Apologies, we are using BBR version bbr version 1.2.2

**Comment by alamages** [comment]
> Hi,
> Apologies, we are using BBR version bbr version 1.2.2
> 

Can you please update to the latest bbr cli, specifically bbr [1.5.2](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases/tag/v1.5.2). 

> Is there some proposed reason why running cleanup might cause an issue?

No. The only reason I can think of is that a cleanup runs(or not finished) at the same time a backup is taken.

Let us know how your backup fails if:
- using the latest bbr cli 
- and only running cleanup when backup fails

 Thanks!

**Comment by keithkroeger** [comment]
Hello,
After making the changes that you proposed, we haven't seen this issue again.
Thank you for your help,
Keith
