### ISSUE TITLE
BBR send errors to file and not stderr

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry-incubator/bosh-backup-and-restore#34]
when running this command:
`$bbrCmd deployment --target $boshIP --username $bbrUser --password $bbrPass --deployment $thisGuid --ca-cert $rootPEM pre-backup-check > /dev/null 2> /dev/null
`
 If the deployment does not have backup scripts, the file below is produced.
`
cat bbr-2020-02-11T18\:59\:06Z.err.log
1 error occurred:
error 1:
Deployment 'my-deployment-GUID' has no backup scripts
github.com/cloudfoundry-incubator/bosh-backup-and-restore/orchestrator.(*BackupableStep).Run
	/tmp/build/80754af9/bosh-backup-and-restore/orchestrator/backupable_step.go:21
github.com/cloudfoundry-incubator/bosh-backup-and-restore/orchestrator.(*Workflow).Run
	/tmp/build/80754af9/bosh-backup-and-restore/orchestrator/workflow.go:17
github.com/cloudfoundry-incubator/bosh-backup-and-restore/orchestrator.BackupChecker.Check
	/tmp/build/80754af9/bosh-backup-and-restore/orchestrator/backup_checker.go:25
github.com/cloudfoundry-incubator/bosh-backup-and-restore/cli/command.backupableCheck
	/tmp/build/80754af9/bosh-backup-and
restore/cli/command/deployment_pre_backup_check.go:64
github.com/cloudfoundry-incubator/bosh-backup-and
restore/cli/command.DeploymentPreBackupCheck.Action
	/tmp/build/80754af9/bosh-backup-and
restore/cli/command/deployment_pre_backup_check.go:51
github.com/urfave/cli.HandleAction
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210
github.com/urfave/cli.(*App).RunAsSubcommand
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:379
github.com/urfave/cli.Command.startApp
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:298
github.com/urfave/cli.Command.Run
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:98
github.com/urfave/cli.(*App).Run
	/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255
main.main
	/tmp/build/80754af9/bosh-backup-and-restore/cmd/bbr/main.go:73
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1357
`

I would expect this output to stdout, and not to a self-defined file.

**Comment by totherme** [comment]
Hi Donald,

We've heard this feedback from a couple of places now, and it's definitely on our radar. We're focussing on other features right now, but we'll circle back around and update this issue when we're able to properly update our bbr UX.

Thanks!

**Comment by neil-hickey** [comment]
Closing for now, the team does not have bandwidth to action this issue.
