### ISSUE TITLE
Stdout doesn't return with bbr cli

### ISSUE THREAD

**Issue by SergeyMuha** [cloudfoundry-incubator/bosh-backup-and-restore#35]
As I understood from docs https://docs.cloudfoundry.org/bbr/bbr-devguide.html#logs, we can get stderr and stdout only in case of script failure.
The stdout and stderr streams are captured and sent to the operator who invokes the backup and restore.
Note: BBR prints any output from the scripts in case of failure.
Here is simple example of backup script that I trigger with bbr cli
 cat backup 
#!/bin/bash
echo "Stdout" 
echo "Stderror" >&2
exit 1
When I run it with bbr cli
bbr deployment   --target $BOSH_ENVIRONMENT   --username $BOSH_CLIENT   --password $BOSH_CLIENT_SECRET   --deployment 688be997ccbfafc76822  backup
[bbr] 2020/04/08 13:20:51 INFO .....
[bbr] 2020/04/08 13:21:26 ERROR - Error backing up broker on job/bffdc9a6-342b-41d0-96ea-bf0dd02acfb5.
.....
1 error occurred:
error 1:
1 error occurred:
error 1:
Error attempting to run backup for job broker on job/bffdc9a6-342b-41d0-96ea-bf0dd02acfb5: Stderror - exit code 1
I get only "Stderror" from stderr, but where is stdout? (edited) 

I can add --debug but it will output much more info then I need. (all calls).
Also how can I get some logs when backup finished successfully?

**Comment by totherme** [comment]
Hi Sergey,

We've heard this feedback from a couple of places now, and it's definitely on our radar. We're focussing on other features right now, but we'll circle back around and update this issue when we're able to properly update our bbr UX.

Thanks!

**Comment by neil-hickey** [comment]
Closing for now, the team does not have bandwidth to action this issue.
