### ISSUE TITLE
v1.9.4 `bbr version` does not reply with a valid semver

### ISSUE THREAD

**Issue by gkspranger** [cloudfoundry-incubator/bosh-backup-and-restore#84]
![image](https://user-images.githubusercontent.com/2514988/112002809-aa60f180-8af6-11eb-831e-101e770c1f3b.png)

some repos of Concourse BBR pipelines expect a valid semver when issuing `bbr version` -- thus breaking said pipelines

https://github.com/pivotal-cf/bbr-pcf-pipeline-tasks

```bash
1 error occurred:
error 1:
failed to find instances for deployment cf-abc123: couldn't find jobs: An error occurred while running metadata script for job s3-unversioned-blobstore-backup-restorer on backup_restore/abc123: Error: BBR version must be a valid semVer - exit code 1
```

**Comment by jak74** [comment]
I was just coming to open the same issue.

**Comment by neil-hickey** [comment]
Hey @gkspranger / @jak74 thanks for bringing this to our attention, I am just going to have a look and will get back to you once the cause has been found. Thanks again!

**Comment by neil-hickey** [comment]
Hi again @gkspranger / @jak74 , I have updated the released 1.9.4 binaries to include the fix. Please let us know if you have any further issues.

**Comment by jak74** [comment]
@neil-hickey - the updated version works as expected.  However, is there any chance that the version number can get bumped?  Keeping the same version number causes issues with resource caching in Concourse, and I believe the only way to resolve would be to recreate numerous workers across multiple Concourse installations.

**Comment by neil-hickey** [comment]
Hey @jak74 , gotcha. Another person has also pointed this out. I think ideally concourse would provide a way to not used a cached version, but given that this is an issue for multiple people it makes sense to publish a new 1.9.5. We will create a story for publishing a new release.

**Comment by neil-hickey** [comment]
Hi @jak74 we have gone ahead and published a new version which should contains the fix. Please let us know if that works / there are any further issues.

**Comment by jak74** [comment]
@neil-hickey thanks for the version bump.  bbr executes correctly, and Concourse is happy.  All is well in the world again.  I agree that it would be nice to be able to invalidate a resource in cache on Concourse, but it appears that the request has been raised more than once and eventually nothing comes of it.
