### ISSUE TITLE
bbr script execution should be either fully deterministic or reliably pseudorandom

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry-incubator/bosh-backup-and-restore#9]
From the routing team's experience, it appears that `bbr` executes scripts in a pseudo-deterministic order.  On a given deployment, the scripts are always executed in the same order each time.  But no two deployments will see the same order.

When a development team is testing `bbr` on a single deployment, they may come to rely on the implicit ordering on their environment.  They may accidentally write order-dependent scripts, and be unaware of it, because the order never changes on their test environment.  When that order-dependent script is deployed elsewhere (e.g. on a customer environment) then it may fail.

One data point: Go intentionally randomizes the order of iteration over `map`s, so that programmers do not accidentally write order-dependent code ([reference](https://blog.golang.org/go-maps-in-action)).

Maybe `bbr` should also fully-randomize the execution order?

Alternately, maybe it should use the explicit job ordering in the relevant BOSH deployment manifest.

cc @cloudfoundry-incubator/cf-routing

**Comment by tinygrasshopper** [comment]
@rosenhouse currently `bbr` would call scripts in a order on the vms given by the bosh api. After giving it some thought, we think it might be helpful for the order to be random, as it might help us catch more issues. I can have a chat to get this prioritized. 

btw, which scripts did you have ordering dependencies on, the lock scripts or the actual backup scripts? bbr allows release authors to explicitly specify declare ordering for the lock scripts(more on that [here](https://docs.pivotal.io/bbr/bbr-devguide.html#script-ordering))
